### ISSUE TITLE
Restore the Community Articles section

### ISSUE THREAD

**Issue by mike-myers-tob** [osql/osql-site#2]
https://osql.io/blog/community-articles should feature all of the latest community articles, and older ones including https://medium.com/palantir/auditing-with-osquery-part-one-introduction-to-the-linux-audit-framework-217967cec406
and
https://medium.com/palantir/auditing-with-osquery-part-two-configuration-and-implementation-87a8bba0ef48

and Trail of Bits' blog posts.

**Comment by mike-myers-tob** [comment]
Include the osql.io announcement blog post too. 😀

https://blog.trailofbits.com/2019/04/18/announcing-the-community-oriented-osquery-fork-osql/

**Comment by Smjert** [comment]
> Include the osql.io announcement blog post too. 
> 
> https://blog.trailofbits.com/2019/04/18/announcing-the-community-oriented-osquery-fork-osql/

I will put that under official-news, since it's more related to the project/development.
Do we want to keep old osquery related official news?

**Comment by mike-myers-tob** [comment]
Ok I suppose you are right, the osql announcement more belongs under news (although it is also about the community). It can go in news.

**Comment by Smjert** [comment]
I think there's a bit of confusion due to how the website is structured.
I actually also have a couple of doubts about the community articles.

So the issues is that community events is meant to be an actual event that happens on a specific day, in a physical place and it's presented with a date, title/external link to something that explains the event better, and a place.
So putting a link to a blogpost there, as it is right now, doesn't make much sense, unless it's an event as for QueryCon.

Official News instead is made for news on the development, but they are not links, they are full articles. We would have to mirror the entire osql announcement blogpost, or I could just put a short sentence and a link to our blog.

Community Articles are full articles too, but in this case we clearly cannot mirror an external article, so a title and a link to the external one should do I think.

What do you think?

**Comment by mike-myers-tob** [comment]
Ok. 

- [ ] On the Community Events page, just a QueryCon announcement blog post link is fine.
- [ ] Official news, we'll start fresh and just delete the old content. The project news will start with the osql announcement. I know we'd have to rewrite it in Markdown so if that's too much work, then a snippet with a link is fine. We'll try to coordinate better with future osql blog posts.
- [ ] Community articles, we can do the same: title and link for now. We can discuss how to embed full articles later.
